#
#   ┏━━━━━━━━━━━━━━━━━━━━━━━━ ⊹ ☆ ⊹ ━━━━━━━━━━━━━━━━━━━━━━━━┓
#
#                        Dungeon Designer
#        Source: https://github.com/WIX3Y/DungeonDesigner
#                          Author: WIX3Y
#
#   ┗━━━━━━━━━━━━━━━━━━━━━━━━ ⊹ ☆ ⊹ ━━━━━━━━━━━━━━━━━━━━━━━━┛
#
#   ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#
#                      List of Placeholders
#
#                        DD_time_<dungeon>
#         Player's fastest completion for specific dungeon
#              Example usage: %DD_time_testdungeon%
#
#                     DD_completion_<dungeon>
#     Player's max completion percentage for specific dungeon
#            Example usage: %DD_completion_testdungeon%
#
#                     DD_numb_runs_<dungeon>
#     Player's number of completed runs for specific dungeon
#            Example usage: %DD_numb_runs_testdungeon%
#
#   ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
#
#   ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#
#                        List of Commands
#
#              ddstart <dungeon> <instance> <player>
#            Start a dungeon run for a specific player
#           Required permission: dungeondesigner.manage
#           Example usage: /ddstart TestDungeon 1 WIX3Y
#
#        ddunlock <dungeon> <instance> <reward-id> <player>
#         Unlocks a dungeon gate and reward for a specific
#                    player running a dungeon
#           Required permission: dungeondesigner.manage
#          Example usage: /ddunlock TestDungeon 1 0 WIX3Y
#
#             ddreward <dungeon> <instance> <player>
#       Sets a dungeon as completed for a player, calculating
#          the dungeon run time and closing the main gate
#           Required permission: dungeondesigner.manage
#           Example usage: /ddreward TestDungeon 1 WIX3Y
#
#              ddend <dungeon> <instance> <player>
#        Stops a dungeon run and sets dungeon as unoccupied
#           Required permission: dungeondesigner.manage
#           Example usage: /ddend TestDungeon 1 WIX3Y
#
#           ddaddreward <dungeon-id> <reward-id> <chance>
#         Add a reward to a specific loot chest loot table
#                     for a specific dungeon
#          Required permission: dungeondesigner.addreward
#           Example usage: /ddaddreward TestDungeon 0 1
#
#                           ddreload
#           Reloads the config file, a server restart is
#            required to apply changes to the database
#           Required permission: dungeondesigner.reload
#                    Example usage: /ddreload
#
#   ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
#

# Do not change
config-version: 1

MySQL:
  ip: localhost
  port: 3306
  database: dungeon_designer
  username: root
  password: password
  poolsize: 10
  updatefreq: 2000 # How often to write to mysql database in ticks
